version: "3"

services:
  mysql101:
    container_name: mysql101
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data/mysql101:/var/lib/mysql
      - ./mysql/data/101:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=adminadmin
  mysql102:
    container_name: mysql102
    image: mysql:5.7
    restart: always
    ports:
      - 3316:3306
    volumes:
      - ./mysql/data/mysql102:/var/lib/mysql
      - ./mysql/data/102:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=adminadmin